set(PROJECT_PLUGINS
  Plugins/my.cemrgproject.cemrgapp:ON  
  Plugins/my.cemrgproject.easi:ON
  Plugins/my.cemrgproject.festive:ON
  Plugins/my.cemrgproject.mmcwplugin:ON
  Plugins/my.cemrgproject.mmeasurement:ON
  Plugins/my.cemrgproject.scar:ON
  Plugins/my.cemrgproject.wathca:ON
  Plugins/my.cemrgproject.renderwindoweditor:OFF
)
